title: Amani's Homepage
description: Home for my projects, bookmark to keep an eye on projects.
markdown: kramdown

# for atom feed
author:
  name: Amani White
  email: amani_g_addison@hotmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
